# Generated by Django 6.1 on 2026-09-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('job_role', models.CharField(blank=True, max_length=50, null=True)),
                ('experience_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('availability_status', models.CharField(blank=True, max_length=20, null=True)),
                ('workload_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('active_tasks', models.IntegerField(blank=True, null=True)),
                ('performance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'projects',
                'managed': True,
            },
        ),
    ]
