# Generated by Django 6.1.1 on 2026-09-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('budget_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vendor_name', models.CharField(default='Unknown', max_length=200)),
                ('payment_method', models.CharField(default='Bank Transfer', max_length=50)),
                ('expense_date', models.DateField(null=True)),
                ('expense_priority', models.CharField(default='Medium', max_length=20)),
                ('approval_status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget_allocated', models.FloatField(default=0)),
                ('budget_limit', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'finance_module_expense',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('vendor_name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(blank=True, default='Cash', max_length=50, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'finance_module_invoice',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('limit_amount', models.FloatField()),
                ('used_amount', models.FloatField(default=0)),
                ('period', models.CharField(default='2026-Q1', max_length=20)),
                ('source', models.CharField(default='csv', max_length=20)),
                ('budget_limit', models.FloatField(blank=True, default=0, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'finance_module_budget',
                'unique_together': {('department', 'category')},
            },
        ),
    ]
