# Generated by Django 6.1.1 on 2026-09-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='budget_limit',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='budget_allocated',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='budget_limit',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='budget_used',
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
