# Generated by Django 6.1.1 on 2026-09-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_module', '0002_remove_budget_amount_remove_budget_budget_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='created_at',
        ),
        migrations.AddField(
            model_name='expense',
            name='budget_allocated',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='budget_limit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='budget_used',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.CharField(default='2024-01-01', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(default='Cash', max_length=50),
        ),
    ]
