# Generated by Django 6.1.1 on 2026-09-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_module', '0003_remove_expense_created_at_expense_budget_allocated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_id']},
        ),
        migrations.AddField(
            model_name='invoice',
            name='expense_date',
            field=models.CharField(default='2024-01-01', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vendor',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='approval_status',
            field=models.CharField(db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='department',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vendor_name',
            field=models.CharField(db_index=True, default='Unknown', max_length=200),
        ),
    ]
